server:
  port: 8082

spring:
  application:
    name: sockets
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    # password: admin
    password: laloserver00
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: newera

app:
  sockets:
    binance-enabled: false
    eod-enabled: true
    binance-url: "wss://stream.binance.us:9443/ws"
    eod-forex-url: "wss://ws.eodhistoricaldata.com/ws/forex"
    eod-us-url: "wss://ws.eodhistoricaldata.com/ws/us-quote"
    eod-token: "68b09a16609891.62026589"
